### ISSUE TITLE
Grounder doesn't handle non-ascii labels well

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/ontogpt#160]
E.g. for the example in #159 

...Sjögren's Syndrome...

```
  - id: AUTO:Sj%C3%B6gren%27s%20Syndrome
    label: Sjögren's Syndrome
```

fails to match on

```yaml
name: Sjogren syndrome
synonym: "Sjogren syndrome" EXACT []
synonym: "Sjögren syndrome" EXACT []
synonym: "Sjögren-Gougerot syndrome" EXACT []
synonym: "primary Sjogren-Gougerot syndrome" EXACT []
synonym: "primary Sjögren-Gougerot syndrome" EXACT []
synonym: "sicca syndrome" EXACT []
synonym: "syndrome, Sjogren's" EXACT []
synonym: "xerodermosteosis" EXACT []
synonym: "Sjogren's syndrome" RELATED []
synonym: "primary Sjögren syndrome" RELATED []
```
