### ISSUE TITLE
Allow partial term matching/exact synoniems

### ISSUE THREAD

**Issue by rickbeeloo** [monarch-initiative/ontogpt#280]
Hey Harry!

I noticed that GPT will provide the full name of foods, for example take this input:
"Sample from Samso Cheese" (Apparently[ a cheese from Denmark](https://en.wikipedia.org/wiki/Sams%C3%B8_cheese)).

It will extract `foods: Samso cheese`, which is correct but since this term isn't in FOODON (exactly) it will not be mapped:
```
named_entities:
  - id: AUTO:cheese
    label: cheese
  - id: AUTO:Samso%20cheese
    label: Samso cheese
```

Bioportal on the other hand correctly maps this to "Cheese food product"([FOODON_00001013](http://purl.obolibrary.org/obo/FOODON_00001013)) (note exact synonym is "cheese" in the entry)

So my questions would be:
- Are these missed cause OntoGPT does an exact matching?
- If so, can we use Bioportal annotator instead?
