### ISSUE TITLE
Show original label from matched entities in extraction results

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#318]
Extractions currently show results like so:
```yaml
prompt: |+
  Split the following piece of text into fields in the following format:

  phenotypes: <A semicolon-separated list of human phenotypes, including symptoms of disease. It must be semicolon-separated. Labels containing the word 'with' should be split into multiple phenotypes.>
  label: <The label (name) of the named thing>


  Text:
  the patient had a middle ear infection

  ===

extracted_object:
  id: 53239082-f074-4ca5-9eeb-49dd2095de35
  label: patient
  phenotypes:
    - HP:0000388
named_entities:
  - id: HP:0000388
    label: middle ear infection
```

In this case, the `label` shown is from the input text, but the HP label for `HP:0000388` is `Otitis media`.
The results should show which labels are from synonyms (as in this case) or are exact matches.

per convo with @twhetzel
