### ISSUE TITLE
Preprocess to remove brackets and other punctuation before attempting grounding

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#323]
A recurring issue: instances where the LLM adds extra formatting/punctuation tend to break things. Example:
```
  patient_weight:
    value: <45 kg; 35 kg>
    unit: AUTO:%3Ckg%3B%20kg%3E
    percentile: <46%; 6%>
    zscore: <-0.10; -1.55>
```
This will probably need to be handled in the SPIRES implementation itself as a post-processing step.

_Originally posted by @caufieldjh in https://github.com/monarch-initiative/ontogpt/issues/319#issuecomment-1930933446_
