### ISSUE TITLE
Followup on #353 - support including annotations in schemas to model KGX output

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#356]
Schemas may currently be annotated with the `owl` slot to denote the OWL equivalent, e.g., in the `recipe` schema:

```yaml
  FoodItem:
    is_a: CompoundExpression
    annotations:
      owl: IntersectionOf
    attributes:
      food:
        description: the food item
        range: FoodType
        slot_uri: BFO:0000051
        annotations:
          owl: ObjectProperty, ObjectSomeValuesFrom
      state:
        description: the state of the food item (e.g. chopped, diced)
        annotations:
          owl: DataProperty, DataHasValue
```

This only comes into play when serializing as OWL.

We can do the same for KGX, as the schema does not define whether a class defines a node, edge, higher-level association, etc.
The annotations field should be able to accept explicit directions for what should be subject, predicate, object and properties.

Perhaps this should be present elsewhere in the LinkML infrastructure.
