### ISSUE TITLE
gpt-4o

### ISSUE THREAD

**Issue by rkboyce** [monarch-initiative/ontogpt#376]
Hi  -  I am trying to add GPT-4o to the ./src/ontogpt/models.yaml per below but am getting an error message: 

```
KeyError: 'Could not automatically map gpt-4o-2024-05-13 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'
```

YAML addition: 
```
- name: MODEL_GPT_4o                                                                                                                                    
    canonical_name: "gpt-4o-2024-05-13"                                                                                                                  
    alternative_names:                                                                                                                                   
      - "gpt-4o-2024-05-13"                                                                                                                              
    provider: OpenAI                                                                                                                                     
    creators:                                                                                                                                            
      - OpenAI                                                                                                                                           
    requirements:                                                                                                                                        
      diskspace: "N/A"                                                                                                                                   
      memory: "N/A"                                                                                                                                      
    is_default: true          
```

Could you please suggest a way forward?

Thanks!
